// <auto-generated />
using System;
using CMS_BE.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CMS_BE.Infrastructure.Data.Migrations
{
    [DbContext(typeof(TheDbContext))]
    [Migration("20250907100309_20250907170305_Migration")]
    partial class _20250907170305_Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CMS_BE.Domain.Aggregates.Auth.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<short>("Role")
                        .HasColumnType("smallint")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("username");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_account");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_account_email");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_account_id");

                    b.HasIndex("PasswordHash")
                        .HasDatabaseName("ix_account_password_hash");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_account_username");

                    b.ToTable("account", (string)null);
                });

            modelBuilder.Entity("CMS_BE.Domain.Aggregates.Auth.AccountToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_account_token");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_account_token_account_id");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_account_token_id");

                    b.ToTable("account_token", (string)null);
                });

            modelBuilder.Entity("CMS_BE.Domain.Aggregates.Humans.Contact", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("patient_id");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.HasKey("Id")
                        .HasName("pk_contact");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_contact_id");

                    b.HasIndex("PatientId")
                        .IsUnique()
                        .HasDatabaseName("ix_contact_patient_id");

                    b.ToTable("contact", (string)null);
                });

            modelBuilder.Entity("CMS_BE.Domain.Aggregates.Humans.Patient", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<int>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<short>("Gender")
                        .HasColumnType("smallint")
                        .HasColumnName("gender");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_patient");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_patient_id");

                    b.ToTable("patient", (string)null);
                });

            modelBuilder.Entity("CMS_BE.Domain.Aggregates.Humans.Prescription", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Dosage")
                        .HasColumnType("text")
                        .HasColumnName("dosage");

                    b.Property<string>("DrugId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("drug_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("UnitId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("unit_id");

                    b.Property<string>("VisitId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("visit_id");

                    b.HasKey("Id")
                        .HasName("pk_prescription");

                    b.HasIndex("DrugId")
                        .HasDatabaseName("ix_prescription_drug_id");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_prescription_id");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_prescription_unit_id");

                    b.HasIndex("VisitId")
                        .HasDatabaseName("ix_prescription_visit_id");

                    b.ToTable("prescription", (string)null);
                });

            modelBuilder.Entity("CMS_BE.Domain.Aggregates.Humans.Visit", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("diagnosis");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("patient_id");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("symptoms");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<DateTimeOffset>("VisitDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("visit_date");

                    b.Property<string>("VisitId")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("visit_id");

                    b.HasKey("Id")
                        .HasName("pk_visit");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_visit_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_visit_patient_id");

                    b.HasIndex("VisitId")
                        .HasDatabaseName("ix_visit_visit_id");

                    b.ToTable("visit", (string)null);
                });

            modelBuilder.Entity("CMS_BE.Domain.Aggregates.Materials.Drug", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<decimal>("Stock")
                        .HasColumnType("numeric")
                        .HasColumnName("stock");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_drug");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_drug_id");

                    b.ToTable("drug", (string)null);
                });

            modelBuilder.Entity("CMS_BE.Domain.Aggregates.Materials.Unit", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DrugId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("drug_id");

                    b.Property<int>("Multiple")
                        .HasColumnType("integer")
                        .HasColumnName("multiple");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_unit");

                    b.HasIndex("DrugId")
                        .HasDatabaseName("ix_unit_drug_id");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_unit_id");

                    b.ToTable("unit", (string)null);
                });

            modelBuilder.Entity("CMS_BE.Domain.Aggregates.Auth.AccountToken", b =>
                {
                    b.HasOne("CMS_BE.Domain.Aggregates.Auth.Account", null)
                        .WithMany("AccountToken")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_token_account_account_id");
                });

            modelBuilder.Entity("CMS_BE.Domain.Aggregates.Humans.Contact", b =>
                {
                    b.HasOne("CMS_BE.Domain.Aggregates.Humans.Patient", "Patient")
                        .WithOne("Contact")
                        .HasForeignKey("CMS_BE.Domain.Aggregates.Humans.Contact", "PatientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_contact_patient_patient_id");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("CMS_BE.Domain.Aggregates.Humans.Prescription", b =>
                {
                    b.HasOne("CMS_BE.Domain.Aggregates.Materials.Drug", "Drug")
                        .WithMany("Prescriptions")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prescription_drug_drug_id");

                    b.HasOne("CMS_BE.Domain.Aggregates.Materials.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prescription_unit_unit_id");

                    b.HasOne("CMS_BE.Domain.Aggregates.Humans.Visit", "Visit")
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prescription_visit_visit_id");

                    b.Navigation("Drug");

                    b.Navigation("Unit");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("CMS_BE.Domain.Aggregates.Humans.Visit", b =>
                {
                    b.HasOne("CMS_BE.Domain.Aggregates.Humans.Patient", "Patient")
                        .WithMany("Visits")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_visit_patient_patient_id");

                    b.HasOne("CMS_BE.Domain.Aggregates.Humans.Visit", null)
                        .WithMany("Visits")
                        .HasForeignKey("VisitId")
                        .HasConstraintName("fk_visit_visit_visit_id");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("CMS_BE.Domain.Aggregates.Materials.Unit", b =>
                {
                    b.HasOne("CMS_BE.Domain.Aggregates.Materials.Drug", "Drug")
                        .WithMany("Units")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_unit_drug_drug_id");

                    b.Navigation("Drug");
                });

            modelBuilder.Entity("CMS_BE.Domain.Aggregates.Auth.Account", b =>
                {
                    b.Navigation("AccountToken");
                });

            modelBuilder.Entity("CMS_BE.Domain.Aggregates.Humans.Patient", b =>
                {
                    b.Navigation("Contact")
                        .IsRequired();

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("CMS_BE.Domain.Aggregates.Humans.Visit", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("CMS_BE.Domain.Aggregates.Materials.Drug", b =>
                {
                    b.Navigation("Prescriptions");

                    b.Navigation("Units");
                });
#pragma warning restore 612, 618
        }
    }
}
